export const digits = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
export const letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
    'u', 'v', 'w', 'x', 'y', 'z']
export const vowels = ['a', 'e', 'i', 'o', 'u']

export const unwantedCharacters = ["'", '"', '`', '~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')',
    '-', '_', '+', '=', '{', '}', '[', ']', '|', '\\', ':', ';', '<', '>', ',', '.', '?', '/',
    '  ', '  ']

export const unwantedWords = [
    "a",
    "aboard",
    "about",
    "above",
    "across",
    "after",
    "against",
    "along",
    "amid",
    "among",
    "am",
    "an",
    "are",
    "around",
    "as",
    "at",
    "be",
    "before",
    "behind",
    "being",
    "below",
    "beneath",
    "beside",
    "between",
    "beyond",
    "but",
    "by",
    "concerning",
    "considering",
    "despite",
    "down",
    "during",
    "except",
    "following",
    "for",
    "from",
    "how",
    "in",
    "inside",
    "into",
    "is",
    "like",
    "many",
    "minus",
    "near",
    "next",
    "of",
    "off",
    "on",
    "onto",
    "opposite",
    "out",
    "outside",
    "over",
    "past",
    "per",
    "plus",
    "regarding",
    "round",
    "save",
    "shall",
    "since",
    "than",
    "the",
    "through",
    "till",
    "to",
    "toward",
    "under",
    "underneath",
    "unlike",
    "until",
    "up",
    "upon",
    "versus",
    "via",
    "was",
    "were",
    "what",
    "while",
    "which",
    "when",
    "where",
    "who",
    "whom",
    "why",
    "will",
    "with",
    "within",
    "without",
]